apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: config-ingress
  namespace: quiz
spec:
  ingressClassName: nginx
  rules:
    - host: config.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: config-service
                port:
                  number: 80
