apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudhinms/quiz-manifest.git
    targetRevision: main
    path: applications/apps/config-service
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
